package com.example.androiddev.book_module

import com.google.gson.annotations.SerializedName

data class BookModel (

    @SerializedName("numFound") var numFound : String = "",
    @SerializedName("start") var start : String = "",
    @SerializedName("numFoundExact") var numFoundExact : Boolean = false,
    @SerializedName("docs") var docs : List<Docs> = emptyList(),
    @SerializedName("num_found") var num_Found : String = "",
    @SerializedName("q") var q : String = "",
    @SerializedName("offset") var offset : String = "",

)

data class Docs (

    @SerializedName("author_alternative_name") var authorAlternativeName : List<String> = emptyList(),
    @SerializedName("author_key") var authorKey : List<String> = emptyList(),
    @SerializedName("author_name") var authorName : List<String> = emptyList(),
    @SerializedName("contributor") var contributor : List<String> = emptyList(),
    @SerializedName("cover_edition_key") var coverEditionKey : String = "",
    @SerializedName("cover_i") var coverI : Int = 0,
    @SerializedName("ddc") var ddc : List<String> = emptyList(),
    @SerializedName("ebook_access") var ebookAccess : String = "",
    @SerializedName("ebook_count_i") var ebookCountI : Int = 0,
    @SerializedName("edition_count") var editionCount : Int = 0,
    @SerializedName("edition_key") var editionKey : List<String> = emptyList(),
    @SerializedName("first_publish_year") var firstPublishYear : Int = 0,
    @SerializedName("first_sentence") var firstSentence : List<String> = emptyList(),
    @SerializedName("format") var format : List<String> = emptyList(),
    @SerializedName("has_fulltext") var hasFulltext : Boolean = false,
    @SerializedName("ia") var ia : List<String> = emptyList(),
    @SerializedName("ia_collection") var iaCollection : List<String> = emptyList(),
    @SerializedName("ia_collection_s") var iaCollectionS : String = "",
    @SerializedName("isbn") var isbn : List<String> = emptyList(),
    @SerializedName("key") var key : String = "",
    @SerializedName("language") var language : List<String> = emptyList(),
    @SerializedName("last_modified_i") var lastModifiedI : Int = 0,
    @SerializedName("lcc") var lcc : List<String> = emptyList(),
    @SerializedName("lccn") var lccn : List<String> = emptyList(),
    @SerializedName("number_of_pages_median") var numberOfPagesMedian : Int = 0,
    @SerializedName("oclc") var oclc : List<String> = emptyList(),
    @SerializedName("printdisabled_s") var printdisabledS : String = "",
    @SerializedName("public_scan_b") var publicScanB : Boolean = false,
    @SerializedName("publish_date") var publishDate : List<String> = emptyList(),
    @SerializedName("publish_place") var publishPlace : List<String> = emptyList(),
    @SerializedName("publish_year") var publishYear : List<Int> = emptyList(),
    @SerializedName("publisher") var publisher : List<String> = emptyList(),
    @SerializedName("seed") var seed : List<String> = emptyList(),
    @SerializedName("title") var title : String = "",
    @SerializedName("title_sort") var titleSort : String = "",
    @SerializedName("title_suggest") var titleSuggest : String = "",
    @SerializedName("type") var type : String = "",
    @SerializedName("id_librarything") var idLibrarything : List<String> = emptyList(),
    @SerializedName("id_goodreads") var idGoodreads : List<String> = emptyList(),
    @SerializedName("id_overdrive") var idOverdrive : List<String> = emptyList(),
    @SerializedName("subject") var subject : List<String> = emptyList(),
    @SerializedName("place") var place : List<String> = emptyList(),
    @SerializedName("person") var person : List<String> = emptyList(),
    @SerializedName("ia_loaded_id") var iaLoadedId : List<String> = emptyList(),
    @SerializedName("ia_box_id") var iaBoxId : List<String> = emptyList(),
    @SerializedName("ratings_average") var ratingsAverage : Double = 0.0,
    @SerializedName("ratings_sortable") var ratingsSortable : Double = 0.0,
    @SerializedName("ratings_count") var ratingsCount : Int = 0,
    @SerializedName("ratings_count_1") var ratingsCount1 : Int = 0,
    @SerializedName("ratings_count_2") var ratingsCount2 : Int = 0,
    @SerializedName("ratings_count_3") var ratingsCount3 : Int = 0,
    @SerializedName("ratings_count_4") var ratingsCount4 : Int = 0,
    @SerializedName("ratings_count_5") var ratingsCount5 : Int = 0,
    @SerializedName("readinglog_count") var readinglogCount : Int = 0,
    @SerializedName("want_to_read_count") var wantToReadCount : Int = 0,
    @SerializedName("currently_reading_count") var currentlyReadingCount : Int = 0,
    @SerializedName("already_read_count") var alreadyReadCount : Int = 0,
    @SerializedName("publisher_facet") var publisherFacet : List<String> = emptyList(),
    @SerializedName("person_key") var personKey : List<String> = emptyList(),
    @SerializedName("place_key") var placeKey : List<String> = emptyList(),
    @SerializedName("person_facet") var personFacet : List<String> = emptyList(),
    @SerializedName("subject_facet") var subjectFacet : List<String> = emptyList(),
    @SerializedName("_version_") var Version_ : String = "",
    @SerializedName("place_facet") var placeFacet : List<String> = emptyList(),
    @SerializedName("lcc_sort") var lccSort : String = "",
    @SerializedName("author_facet") var authorFacet : List<String> = emptyList(),
    @SerializedName("subject_key") var subjectKey : List<String> = emptyList(),
    @SerializedName("ddc_sort") var ddcSort : String = ""

)